openapi: 3.0.0

components:
  responses:
    "400":
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BadRequestResponse"

    "401":
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UnauthorizedResponse"

    "403":
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ForbiddenResponse"

    "404":
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/NotFoundResponse"

    "409":
      description: Conflict
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ConflictResponse"

    "422":
      description: Validation Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ValidationErrorResponse"

    "500":
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InternalServerErrorResponse"
